"""ActivityPub support

Revision ID: 76ca7cac4cdc
Revises: 2b948713686c
Create Date: 2023-10-15 15:23:08.728927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ca7cac4cdc'
down_revision = '2b948713686c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('private_key', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('private_key')
        batch_op.drop_column('public_key')

    # ### end Alembic commands ###
