"""Users are managers of events

Revision ID: 9a58ab682a87
Revises: 47bfc29a47b4
Create Date: 2024-11-10 00:42:27.122187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a58ab682a87'
down_revision = '47bfc29a47b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('eventmanager', 'users', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('eventmanager', type_='foreignkey')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
