"""add my_ranking to user

Revision ID: be6bc930546b
Revises: f2104842f6b0
Create Date: 2026-02-26 23:31:45.735448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6bc930546b'
down_revision = 'f2104842f6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_my_ranking', sa.UnicodeText(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_my_ranking')

    # ### end Alembic commands ###
