"""Add cc_signal to Project model

Revision ID: cf47d6b6bb32
Revises: 66da53eca449
Create Date: 2025-08-19 20:52:58.058937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf47d6b6bb32'
down_revision = '66da53eca449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cc_signal', sa.String(length=10), nullable=True))

    with op.batch_alter_table('projects_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cc_signal', sa.String(length=10), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_version', schema=None) as batch_op:
        batch_op.drop_column('cc_signal')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('cc_signal')

    # ### end Alembic commands ###
