"""empty message

Revision ID: f2104842f6b0
Revises: 66da53eca449
Create Date: 2025-08-22 15:21:53.192588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2104842f6b0'
down_revision = '66da53eca449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_reuse', sa.String(length=256), nullable=True))

    with op.batch_alter_table('projects_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_reuse', sa.String(length=256), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_version', schema=None) as batch_op:
        batch_op.drop_column('terms_reuse')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('terms_reuse')

    # ### end Alembic commands ###
